### ISSUE TITLE
Fall 2021 Release Checklist

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-backend#662]
This is a list of everything we need to complete as part of this release. Please add what is missing.

### Release Notes:
- [ ] add release notes to Apple Store
- [ ] add release notes to Google stores

### Screenshots:
- [ ] add screenshots to Apple Store
- [ ] add screenshots to Google stores

### Data:
List things that we need to remember to think about when it comes to service data to be part of the organizations release of the app:

- [ ] Review topic-services and keep an eye out for new services that may be missed because they have not been tagged with the old-style bc211 taxonomy terms
- [ ] Import manually crafted CSV files from Jean with school, library, rec centre, etc. data
- [ ] Ensure that manually crafted CSV have primary ids populated, create tool to generate uuids for these if needed
